# Generated by Django 5.2.3 on 2025-06-20 19:15

from django.db import migrations

def create_default_categories(apps, schema_editor):
    """
    Popula o banco de dados com categorias padrão do sistema.
    Estas categorias não são vinculadas a nenhum usuário (usuario=None).
    """
    Categoria = apps.get_model('core', 'Categoria')
    default_categories = [
        'Alimentação',
        'Moradia',
        'Transporte',
        'Saúde',
        'Educação',
        'Lazer',
        'Salário',
        'Investimentos',
        'Outros'
    ]
    for category_name in default_categories:
        Categoria.objects.get_or_create(nome=category_name, usuario=None)

def remove_default_categories(apps, schema_editor):
    """Remove as categorias padrão caso a migração seja revertida."""
    Categoria = apps.get_model('core', 'Categoria')
    default_categories = ['Alimentação', 'Moradia', 'Transporte', 'Saúde', 'Educação', 'Lazer', 'Salário', 'Investimentos', 'Outros']
    for category_name in default_categories:
        Categoria.objects.filter(nome=category_name, usuario=None).delete()

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'), # Certifique-se de que esta dependência corresponde à sua última migração
    ]

    operations = [
        migrations.RunPython(create_default_categories, remove_default_categories),
    ]
