# Generated by Django 5.2.3 on 2025-06-21 21:56

import core.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20250620_2207'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='lancamento',
            name='categoria',
            field=models.ForeignKey(default=core.models.get_default_other_category_pk, help_text='Categoria do lançamento.', on_delete=django.db.models.deletion.PROTECT, to='core.categoria'),
        ),
        migrations.CreateModel(
            name='RegraCategoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto_regra', models.CharField(help_text='Texto a ser procurado na descrição do lançamento (não diferencia maiúsculas/minúsculas).', max_length=200)),
                ('ordem', models.PositiveIntegerField(default=0, help_text='Ordem de prioridade da regra (menor número = maior prioridade).')),
                ('categoria', models.ForeignKey(help_text='Categoria a ser aplicada se o texto for encontrado.', on_delete=django.db.models.deletion.CASCADE, to='core.categoria')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='regras_categoria', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Regra de Categoria',
                'verbose_name_plural': 'Regras de Categoria',
                'ordering': ['ordem'],
                'unique_together': {('usuario', 'texto_regra')},
            },
        ),
    ]
