# Generated by Django 5.2.3 on 2025-06-22 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_lancamento_categoria_regracategoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='lancamento',
            name='recorrencia_id',
            field=models.UUIDField(blank=True, db_index=True, editable=False, help_text='ID que agrupa lançamentos de uma mesma recorrência.', null=True),
        ),
    ]
