# Generated by Django 5.2.3 on 2025-06-20 00:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_popular_categorias_padrao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lancamento',
            name='conta_bancaria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lancamentos', to='core.contabancaria'),
        ),
    ]
