# Generated by Django 5.2.3 on 2025-06-20 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_lancamento_conta_bancaria'),
    ]

    operations = [
        migrations.AddField(
            model_name='lancamento',
            name='import_hash',
            field=models.CharField(blank=True, db_index=True, editable=False, max_length=32, null=True, unique=True),
        ),
    ]
