# Generated by Django 5.2.3 on 2025-06-22 02:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_lancamento_recorrencia_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cartaocredito',
            name='conta_pagamento',
            field=models.ForeignKey(default=1, help_text='Conta bancária usada para pagar a fatura deste cartão.', on_delete=django.db.models.deletion.PROTECT, related_name='cartoes_pagos_por_esta_conta', to='core.contabancaria'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Fatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano_mes_referencia', models.DateField(help_text='Primeiro dia do mês de referência da fatura.')),
                ('data_fechamento', models.DateField()),
                ('data_vencimento', models.DateField()),
                ('valor_total', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('valor_pago', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=15, null=True)),
                ('status', models.CharField(choices=[('ABERTA', 'Aberta'), ('FECHADA', 'Fechada'), ('PAGA', 'Paga')], default='ABERTA', max_length=10)),
                ('cartao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faturas', to='core.cartaocredito')),
                ('lancamento_pagamento', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fatura_paga', to='core.lancamento')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faturas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Fatura',
                'verbose_name_plural': 'Faturas',
                'ordering': ['-data_vencimento'],
                'unique_together': {('cartao', 'ano_mes_referencia')},
            },
        ),
        migrations.AddField(
            model_name='lancamento',
            name='fatura',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lancamentos', to='core.fatura'),
        ),
    ]
