# Generated by Django 5.2.3 on 2025-06-20 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_lancamento_import_hash'),
    ]

    operations = [
        migrations.AddField(
            model_name='lancamento',
            name='numero_documento',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
    ]
