# Generated by Django 5.2.3 on 2025-06-20 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_lancamento_numero_documento'),
    ]

    operations = [
        migrations.AddField(
            model_name='contabancaria',
            name='data_saldo_inicial',
            field=models.DateField(default='2025-05-31', help_text='Data correspondente ao saldo inicial informado.'),
            preserve_default=False,
        ),
    ]
