# Generated by Django 5.2.3 on 2025-06-20 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_contabancaria_data_saldo_inicial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contabancaria',
            name='saldo_calculado',
            field=models.DecimalField(decimal_places=2, default=0.0, editable=False, help_text='Saldo atual calculado via sinais para otimização de performance.', max_digits=15),
        ),
    ]
