# Generated by Django 5.2.3 on 2025-06-20 14:53

import django.db.models.deletion
import encrypted_model_fields.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_contabancaria_saldo_calculado'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConexaoBancaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banco', models.CharField(default='Banco do Brasil', max_length=100)),
                ('access_token', encrypted_model_fields.fields.EncryptedCharField()),
                ('refresh_token', encrypted_model_fields.fields.EncryptedCharField()),
                ('expira_em', models.DateTimeField(help_text='Data e hora de expiração do access_token')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conexoes_bancarias', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('usuario', 'banco')},
            },
        ),
    ]
